### ISSUE TITLE
InterruptedException on startup of NetBeans

### ISSUE THREAD

**Issue by Chris2011** [junichi11/netbeans-encoding-plugin#16]
Hey,

when I start NetBeans and open the messages.log, I got this exception:

```
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
[catch] at org.netbeans.modules.projectapi.nb.NbProjectManager$2.run(NbProjectManager.java:266)
	at org.netbeans.modules.projectapi.nb.NbProjectManager$2.run(NbProjectManager.java:243)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:209)
	at org.openide.util.Mutex.readAccess(Mutex.java:250)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.findProject(NbProjectManager.java:243)
	at org.netbeans.api.project.ProjectManager.findProject(ProjectManager.java:167)
	at org.netbeans.modules.projectapi.SimpleFileOwnerQueryImplementation.getOwner(SimpleFileOwnerQueryImplementation.java:161)
	at org.netbeans.api.project.FileOwnerQuery.getOwner(FileOwnerQuery.java:116)
	at org.netbeans.modules.projectapi.ProjectFileEncodingQueryImplementation.getEncoding(ProjectFileEncodingQueryImplementation.java:72)
	at org.netbeans.api.queries.FileEncodingQuery.getEncoding(FileEncodingQuery.java:96)
	at org.netbeans.modules.html.HtmlDataObject$FileEncodingQueryImpl.getEncoding(HtmlDataObject.java:382)
	at org.netbeans.modules.openide.loaders.DataObjectEncodingQueryImplementation.getEncoding(DataObjectEncodingQueryImplementation.java:118)
	at org.netbeans.api.queries.FileEncodingQuery.getEncoding(FileEncodingQuery.java:96)
	at com.junichi11.netbeans.modules.encoding.ui.EncodingPanel.getEncoding(EncodingPanel.java:210)
	at com.junichi11.netbeans.modules.encoding.ui.EncodingPanel.resultChanged(EncodingPanel.java:174)
	at org.openide.util.lookup.SimpleProxyLookup.checkLookup(SimpleProxyLookup.java:114)
	at org.openide.util.lookup.SimpleProxyLookup.lookup(SimpleProxyLookup.java:159)
	at org.netbeans.modules.openide.windows.GlobalActionContextImpl.blickActionMapImpl(GlobalActionContextImpl.java:132)
	at org.netbeans.modules.openide.windows.GlobalActionContextImpl.blickActionMap(GlobalActionContextImpl.java:106)
	at org.netbeans.modules.openide.windows.GlobalActionContextImpl.propertyChange(GlobalActionContextImpl.java:205)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:328)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.KeyboardFocusManager.firePropertyChange(KeyboardFocusManager.java:1493)
	at java.awt.KeyboardFocusManager.setGlobalPermanentFocusOwner(KeyboardFocusManager.java:780)
	at java.awt.Component.removeNotify(Component.java:6993)
	at java.awt.Container.removeNotify(Container.java:2820)
	at java.awt.Window.removeNotify(Window.java:782)
	at java.awt.Frame.removeNotify(Frame.java:1041)
	at java.awt.Window$1DisposeAction.run(Window.java:1190)
	at java.awt.Window.doDispose(Window.java:1206)
	at java.awt.Window.dispose(Window.java:1147)
	at org.netbeans.core.startup.Splash$SplashRunner.run(Splash.java:642)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Can you please have a look?

Regards

Chris

**Comment by Chris2011** [comment]
And I don't know whether this is a part of it or not too:

```
org.netbeans.core.CLIOptions2$EQStuck: GUI is not responsive
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.netbeans.modules.projectapi.nb.NbProjectManager$2.run(NbProjectManager.java:266)
	at org.netbeans.modules.projectapi.nb.NbProjectManager$2.run(NbProjectManager.java:243)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:209)
	at org.openide.util.Mutex.readAccess(Mutex.java:250)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.findProject(NbProjectManager.java:243)
	at org.netbeans.api.project.ProjectManager.findProject(ProjectManager.java:167)
	at org.netbeans.modules.projectapi.SimpleFileOwnerQueryImplementation.getOwner(SimpleFileOwnerQueryImplementation.java:161)
	at org.netbeans.api.project.FileOwnerQuery.getOwner(FileOwnerQuery.java:116)
	at org.netbeans.modules.projectapi.ProjectFileEncodingQueryImplementation.getEncoding(ProjectFileEncodingQueryImplementation.java:72)
	at org.netbeans.api.queries.FileEncodingQuery.getEncoding(FileEncodingQuery.java:96)
	at com.junichi11.netbeans.modules.encoding.ui.EncodingPanel.getEncoding(EncodingPanel.java:210)
	at com.junichi11.netbeans.modules.encoding.ui.EncodingPanel.resultChanged(EncodingPanel.java:174)
	at org.openide.util.lookup.SimpleProxyLookup.checkLookup(SimpleProxyLookup.java:114)
	at org.openide.util.lookup.SimpleProxyLookup.lookup(SimpleProxyLookup.java:159)
	at org.netbeans.modules.openide.windows.GlobalActionContextImpl.blickActionMapImpl(GlobalActionContextImpl.java:132)
	at org.netbeans.modules.openide.windows.GlobalActionContextImpl.blickActionMap(GlobalActionContextImpl.java:106)
	at org.netbeans.modules.openide.windows.GlobalActionContextImpl.propertyChange(GlobalActionContextImpl.java:205)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:328)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.KeyboardFocusManager.firePropertyChange(KeyboardFocusManager.java:1493)
	at java.awt.KeyboardFocusManager.setGlobalPermanentFocusOwner(KeyboardFocusManager.java:780)
	at java.awt.Component.removeNotify(Component.java:6993)
	at java.awt.Container.removeNotify(Container.java:2820)
	at java.awt.Window.removeNotify(Window.java:782)
	at java.awt.Frame.removeNotify(Frame.java:1041)
	at java.awt.Window$1DisposeAction.run(Window.java:1190)
	at java.awt.Window.doDispose(Window.java:1206)
	at java.awt.Window.dispose(Window.java:1147)
	at org.netbeans.core.startup.Splash$SplashRunner.run(Splash.java:642)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
[catch] at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by junichi11** [comment]
Probably, It doesn't occur now because I removed Exceptions.printStackTrace().
